### ISSUE TITLE
Membership: @Devan Mallory (Professor Felix)

### ISSUE THREAD

**Issue by dman82499** [logicmoo/logicmoo_workspace#26]
To @logicmoo. Saw the link on the website (https://logicmoo.org/xwiki/bin/view/Main/Developer/) and would love to help out sometime. My skills are primarily with python, c++, and prologue, as well as experience with NARS, SOAR, and Cyquential AI.

**Comment by TeamSPoon** [comment]
You have been invited to now to the logicmoo team on github
